Remove lodash dependency
tyv/pick-react-known-prop pull request #1
Opened 2016-12-31 03:03 UTC by Tvrqvoise

This removes the Lodash dependency to decrease the overall size of the dist file from 120K to 16K.

2017-01-03 16:45 UTC, Tvrqvoise commented
@tyv Mind giving this a quick look?  This was kind of a conservative change -- we could potentially also just pass the files through babel instead of bundling them, which would allow webpack to know that the lodash deps are just lodash deps and not to include them twice.

2017-01-03 16:57 UTC, tyv commented
@Tvrqvoise as far as I know with npm 3.x you will not bundle this files twice

2017-01-03 19:47 UTC, Tvrqvoise commented
I'm actually using npm 3.x, but it's not really an npm problem.  It's more related to the files being bundled together and thus no longer able to be optimized by Webpack.

Here's the issue:

When we run Webpack in pick-react-known-props, we take our source files, add a bunch of lodash stuff on top of it, and bundle it into a single dist file.

Later, I import pick-react-known-prop into my project.  My project already depends on the same lodash files.  When I run webpack on my project it sees the lodash files I depend upon and will try to dedup them -- but it doesn't see the lodash files inside pick-react-known-prop, because they're already built into this bundle and are no longer separate files, so it can't touch them.

If you passed your project through Babel directly instead of Webpack, that would also fix the issue because then Webpack would see the actual imports being made by your source files and know how to handle them.  That being said, I don't know if you really need lodash for how small this module is, and adds extra issues, such as locking you to specific versions of that library and so on.

2017-01-04 09:43 UTC, tyv commented
@Tvrqvoise I agree, have few tiny comments regarding code

2017-01-04 09:47 UTC, tyv requested changes

2017-01-04 09:47 UTC, tyv commented on src/lib/pick-props.js
> +const isPlainObject = obj =>
is there a rason why it is not just `function isPlainObject(obj) {}`?

2017-01-04 09:47 UTC, tyv commented on src/lib/pick-props.js
> +
if we put a lodash function replacement, it seems reasonable if it will have own tests.

2017-01-04 09:49 UTC, tyv commented on src/lib/pick-props.js
> +
Ah, we have test with empty array. Think that is enough.

2017-01-04 17:22 UTC, Tvrqvoise commented on src/lib/pick-props.js
> +const isPlainObject = obj =>
Not really -- changed it to a plain function.

2017-01-04 17:24 UTC, Tvrqvoise commented on src/lib/pick-props.js
> +
Didn't see your test, so I ported over a bunch of the tests from lodash.  There were some areas where they weren't quite the same (such as if the object contained a custom defined "constructor" property), so it's probably a good thing in the end.

2017-01-04 17:27 UTC, Tvrqvoise commented
@tyv Okay, updated the PR with requested changes.  Let me know if all looks good.

2017-01-04 19:50 UTC, tyv commented
@Tvrqvoise thank you very much, looks fine. 
I am sorry didn't thought about this before, but if we do the copy of lodash's `isPlainObject` can you  put it in separate file in `./src/lib` folder with name `lodash.is-plain-object.js` please.

2017-01-06 03:32 UTC, Tvrqvoise commented
@tyv Done, let me know if there's anything else or if you want me to squash the commit.

2017-01-06 08:37 UTC, tyv commented
@Tvrqvoise thanks! thats fine, I will do the version today a bit later.

2017-01-06 08:37 UTC, merged

2017-01-06 10:03 UTC, tyv commented
published